### ISSUE TITLE
Erro nas funções de nif, cc e bi

### ISSUE THREAD

**Issue by pedromdpereira** [CubeSkyy/checkCC#1]
Olá!
Para as funções funcionarem é necessário que o input seja já uma string ou fazer a conversão dentro da própria função, à semelhança da função validate_nif() : 
```
def validate_nif(nif):
    nif = str(nif)
```
Resto de bom trabalho!

**Comment by CubeSkyy** [comment]
Obrigado pela ajuda! Irei mudar.
